#!/usr/bin/env bash

SCRIPTNAME=install-arch
BOOTSTRAP_DIR=$(dirname "${BASH_SOURCE}")

# defaults
COUNTRIES=us,ca # -c
HOSTNAME=arch
USERNAME=admin
PASSWORD=admin

error() {
  local msg=${1}
  echo -e "\e[31m${SCRIPTNAME}: $1\e[0m"
  exit -1
}

checkError() {
  if [[ $? -ne 0 ]] ; then
    error "Failed $1"
  fi
}

usage() {
  echo "usage: ${SCRIPTNAME} -d <device> [options...]"
  echo "  options:"
  echo "    -n <hostname=server[.domain]>"
  echo "    -u <username=admin>"
  echo "    -p <password=admin>"
  echo "    -s <public sshkey>"
  echo "    -f <directory containing user files>"
  echo "    -w <wifi SSID>:<password>"

  exit 0
}

setup_mirrors() {
  # update
  pacman -Sy --noconfirm --needed reflector archlinux-keyring
  checkError "initializing pacman"

  # set mirrors
  echo "Setting up reflectors..."
  if [[ ! -f /etc/pacman.d/mirrorlist ]] ; then
    reflector -c "${COUNTRIES}" -f 12 -l 10 -n 12 --save /etc/pacman.d/mirrorlist
    checkError "setting reflectors"
  fi
}

parition_drive() {
  # create partition
  (
    echo g   # Create a new empty GPT partition table
    echo n   # Add a new partition
    echo     # Auto-select partition number
    echo     # Auto-select partition start
    echo +1G # Partition Size
    echo t   # Change type
    echo 1   # EFI parttion
    echo     # Auto-select partition
    echo n   # Add a new partition
    echo     # Auto-select partition number
    echo     # Auto-select partition start
    echo     # Auto-select partition end

    echo w      # Write changes
  ) | fdisk -W always ${DRIVE}
  checkError "partitioning ${DRIVE}"

  if [[ $1 == custom ]] ; then
    if [[ -b ${DRIVE}1 && -b ${DRIVE}2 ]] ; then
      BOOT_PART=${DRIVE}1
      ROOT_PART=${DRIVE}2
    elif [[ -b ${DRIVE}p1 && -b ${DRIVE}p2 ]] ; then
      BOOT_PART=${DRIVE}p1
      ROOT_PART=${DRIVE}p2
    else
      error "Error detecting partitions"
    fi

    mkfs.fat -F32 ${BOOT_PART}
    mkfs.btrfs -L ${hostname} -f ${ROOT_PART}

    mount -t btrfs ${ROOT_PART} ${MOUNT_DIR}

    btrfs subv create ${MOUNT_DIR}/@
    btrfs subv create ${MOUNT_DIR}/@home
    btrfs subv create ${MOUNT_DIR}/@log
    btrfs subv create ${MOUNT_DIR}/@pkg
    btrfs subv create ${MOUNT_DIR}/@.snapshots

    mkdir -p ${MOUNT_DIR}/@/var/lib

    btrfs subv create ${MOUNT_DIR}/@/var/lib/portables
    btrfs subv create ${MOUNT_DIR}/@/var/lib/machines

    btrfs subv list ${MOUNT_DIR}/

    umount ${MOUNT_DIR}

    mount -t btrfs -o rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/@ ${ROOT_PART} ${MOUNT_DIR}

    mkdir -p ${MOUNT_DIR}/home ${MOUNT_DIR}/var/log ${MOUNT_DIR}/var/cache/pacman/pkg ${MOUNT_DIR}/.snapshots ${MOUNT_DIR}/boot

    mount -t btrfs -o rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/@home ${ROOT_PART} ${MOUNT_DIR}/home
    mount -t btrfs -o rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/@log ${ROOT_PART} ${MOUNT_DIR}/var/log
    mount -t btrfs -o rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/@pkg ${ROOT_PART} ${MOUNT_DIR}/var/cache/pacman/pkg
    mount -t btrfs -o rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/@.snapshots ${ROOT_PART} ${MOUNT_DIR}/.snapshots
    mount -t vfat -o rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro ${BOOT_PART} ${MOUNT_DIR}/boot
  fi
}

setup_bridge() {
  interface=$(nmcli device | grep ethernet -m 1 | sort | awk '{print $1}')
  uuid=$(nmcli -f UUID,TYPE con show | grep ethernet -m 1 | sort | awk '{print $1}')
  if [[ -z ${ETH_IP} ]]; then
    ip=$(ip -4 a show dev ${interface} | grep inet -m 1 | awk '{print $2}')
  else
    ip=${ETH_IP}
  fi

  if [[ -z "${interface}" || -z "${uuid}" ]]; then
    return
  fi

  sudo nmcli con mod ${uuid} ifname ${interface} con-name ${interface}
  sudo nmcli con add type bridge ifname br0 con-name br0
  sudo nmcli con add type bridge-slave ifname ${interface} master br0 con-name ${interface}-slave
  if [[ -n ${ip} ]] ; then
    sudo nmcli con mod br0 ipv4.addresses "${ip}" ipv4.dhcp-hostname ${HOSTNAME%%.*} ipv4.ignore-auto-routes no ipv4.ignore-auto-dns no ipv4.method auto
  fi
  sudo nmcli con mod br0 ipv6.method ignore
  sudo nmcli con up br0
  sudo nmcli con up ${interface}-slave
}

setup_wifi() {
  interface=$(nmcli device | grep wifi -m 1 | sort | awk '{print $1}')
  if [[ -z "${interface}" || -z "${WIFI_SSID}" || -z "${WIFI_PASSWORD}" ]]; then
    return
  fi

  psk=$(wpa_passphrase "${WIFI_SSID}" "${WIFI_PASSWORD}" | grep -e "\spsk" | cut -d= -f2)

  sudo nmcli con add type wifi ifname ${interface} ssid "${WIFI_SSID}" con-name ${interface}
  sudo nmcli con mod ${interface} wifi-sec.key-mgmt wpa-psk wifi-sec.psk "${psk}"

  if [[ -n "${WIFI_IP}" ]]; then
    sudo nmcli con mod ${interface} ipv4.addresses "${WIFI_IP}"
  fi

  sudo nmcli con up ${interface}
}

parition_data_drive() {
  if [[ ! -b ${DATA_DRIVE}1 && ! -b ${DATA_DRIVE}p1 ]] ; then
    # create partition
    (
      echo g   # Create a new empty GPT partition table
      echo n   # Add a new partition
      echo     # Auto-select partition number
      echo     # Auto-select partition start
      echo     # Auto-select partition end

      echo w      # Write changes
    ) | fdisk -W always ${DATA_DRIVE}
    checkError "partitioning ${DATA_DRIVE}"
    if [[ -b ${DATA_DRIVE}1 ]] ; then
      DATA_PART=${DATA_DRIVE}1
    elif [[ -b ${DATA_DRIVE}p1 && -b ${DATA_DRIVE}p2 ]] ; then
      DATA_PART=${DATA_DRIVE}p1
    else
      error "Error detecting partitions"
    fi

    mkfs.btrfs -L ${hostname} -f ${DATA_PART}
    checkError "formatting data drive"
  else
    if [[ -b ${DATA_DRIVE}1 ]] ; then
      DATA_PART=${DATA_DRIVE}1
    elif [[ -b ${DATA_DRIVE}p1 && -b ${DATA_DRIVE}p2 ]] ; then
      DATA_PART=${DATA_DRIVE}p1
    fi
  fi

  mkdir -p /mnt/userdata
  mount -t btrfs ${DATA_PART} /mnt/userdata
  checkError "mounting data drive"

  btrfs subv create /mnt/userdata/@home
  btrfs subv create /mnt/userdata/@vms
  btrfs subv create /mnt/userdata/@library
}

setup_data_drive() {
  mount_data_drive

  uuid=$(blkid ${DATA_DRIVE} -o value -s UUID)
  for vol in $(btrfs subv list /mnt/userdata | awk '{print $9}') ; do
    # if vol start with @
    if [[ "${vol}" == "@"* ]] ; then
      mkdir -p ${MOUNT_DIR}/home/${USERNAME}/${vol#\@}
      echo "UUID=${uuid} /home/${USERNAME}/${vol#\@} btrfs rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/${vol},nofail 0 0" >> ${MOUNT_DIR}/etc/fstab
    else
      mkdir -p ${MOUNT_DIR}/${vol}
      echo "UUID=${uuid} /${vol} btrfs rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol=/${vol},nofail 0 0" >> ${MOUNT_DIR}/etc/fstab
    fi
  done
}

arch_install() {
  # log
  LOG_FILE=~/${SCRIPTNAME}.log
  exec > >(tee $LOG_FILE) 2>&1

  cd ${BOOTSTRAP_DIR}

  # setup arch mirrors
  setup_mirrors

  # partition and format target drive
  parition_drive

  PART_SIZE=$(fdisk -l ${DRIVE} | tail -1 | awk '{print $4 * 512}')
  cp -f user_configuration.tpl.json /tmp/user_configuration.json
  sed -e "s#DEV#${DRIVE}#g" -e "s#PART_SIZE#${PART_SIZE}#g" -e "s#HOSTNAME#${HOSTNAME}#g" -i /tmp/user_configuration.json

  cp -f user_credentials.tpl.json /tmp/user_credentials.json
  sed -e "s#PASSWORD#${PASSWORD}#g" -e "s#USERNAME#${USERNAME}#g" -i /tmp/user_credentials.json

  archinstall --config /tmp/user_configuration.json --creds /tmp/user_credentials.json --silent
  checkError "archinstall"

  MOUNT_DIR=/mnt/archinstall

  # sudo
  mkdir -p /etc/sudoers.d
  echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" > ${MOUNT_DIR}/etc/sudoers.d/00_${USERNAME}

  # copy files
  cp /etc/pacman.d/mirrorlist ${MOUNT_DIR}/etc/pacman.d/mirrorlist

  USER_HOME=${MOUNT_DIR}/home/${USERNAME}
  if [[ -d ${USER_FILES} ]] ; then
    cp -ar "${USER_FILES}/." ${USER_HOME}
  elif $(file "${USER_FILES}" | grep -q compressed) ; then
    cd ${USER_HOME}
    tar xf "${USER_FILES}"
    cd -
  elif [[ -f ${USER_FILES} ]] ; then
    cp -a "${USER_FILES}" ${USER_HOME}
  fi

  # ssh key
  if [[ -n ${SSH_KEY} ]] ; then
    mkdir -p ${USER_HOME}/.ssh
    echo "${SSH_KEY}" >> ${USER_HOME}/.ssh/authorized_keys
  fi

  # ownership and permission
  if [[ -d ${USER_HOME}/.ssh ]] ; then
    chmod 700 ${USER_HOME}/.ssh
    chmod 600 ${USER_HOME}/.ssh/*
  fi

  # post install
  mkdir -p ${USER_HOME}/.local/share
  cp -a ../bootstrap ${USER_HOME}/.local/share/bootstrap
  arch-chroot -u ${USERNAME} ${MOUNT_DIR} /home/${USERNAME}/.local/share/bootstrap/install-arch --post-install

  # network
  if [[ -z ${SKIP_NETWORK} ]] ; then
    pacman -Sy --noconfirm networkmanager
    systemctl start NetworkManager
    setup_bridge
    setup_wifi
    mkdir -p ${MOUNT_DIR}/etc/NetworkManager/system-connections
    cp /etc/NetworkManager/system-connections/* ${MOUNT_DIR}/etc/NetworkManager/system-connections/
  fi

  # data-drive
  if [[ -n ${DATA_DRIVE} ]] ; then
    setup_data_drive
  fi
}

install_yay() {
  mkdir -p .aur
  cd .aur

  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si --noconfirm
  checkError "installing yay"
  cd ~
}

post_install() {
  export USER=$(whoami)
  echo "Running post_install as ${USER}"

  export HOME=/home/${USER}
  cd ${HOME}

  sudo chown -R ${USER}:${USER} ${HOME}

  # crontab
  sudo systemctl enable cronie

  # sshd
  sudo systemctl enable sshd.service

  # key for aur
  sudo gpg --keyserver keyserver.ubuntu.com --recv-keys 5C4A26CD4CC8C397

  install_yay

  # install aur apps
  yay -Sy --needed --noconfirm udevil rc-local cpulimit ntfsprogs-ntfs3

  # vi
  sudo rm -f /usr/bin/vi
  sudo ln -s /usr/bin/vim /usr/bin/vi

  # user
  sudo usermod -aG wheel,audio ${USER}

  # aur services
  systemctl --user enable rc-local.service

  # packages
  if [[ -n ${PACKAGES} ]] ; then
    yay -Sy --needed --noconfirm ${PACKAGES}
  fi

  # services
  if [[ -n ${SERVICES} ]] ; then
    sudo systemctl enable ${SERVICES}
  fi

  # user services
  if [[ -n ${USER_SERVICES} ]] ; then
    systemctl --user enable ${USER_SERVICES}
  fi

  # shenv
  if [[ -f ${HOME}/.gitconfig.vm75 ]] ; then
    git clone https://github.com/vm75/shenv.git ${HOME}/.local/share/shenv
    ${HOME}/.local/share/shenv/bin/shenv

    # features
    if [[ -n ${FEATURES} ]] ; then
      ${HOME}/.local/share/shenv/bin/os install ${FEATURES}
    fi
  fi

  exit 0
}

main() {
  if [[ $1 == --post-install ]] ; then
    post_install
  fi

  mkdir -p /mnt/data
  mount -L CIDATA /mnt/data
  if [[ -f /mnt/data/.archinstall ]] ; then
    . /mnt/data/.archinstall
  fi

  while getopts "DNc:d:h" option; do
    case "${option}" in
    D)
      set -x
      ;;
    N)
      SKIP_NETWORK=1
      ;;
    c)
      if [[ ! -f ${OPTARG} ]] ; then
        error "Invalid config file ${OPTARG}"
      fi
      . ${OPTARG}
      ;;
    d)
      if [[ -b /dev/${OPTARG} ]] ; then
        DRIVE="/dev/${OPTARG}"
      elif [[ -b ${OPTARG} ]] ; then
        DRIVE=${OPTARG}
      else
        error "Invalid drive ${OPTARG}"
      fi
      ;;
    h)
      usage
      exit
      ;;
    esac
  done
  shift $((OPTIND-1))

  if [[ -z ${DRIVE} ]] ; then
    error "No valid drive found"
  fi

  arch_install
  echo "All set!"
}

main "$@"
